name: update v3 branch on next changes
on:
  push:
    branches:
      - next
jobs:
  update-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v3
      - name: merge origin/next into v3
        run: |
          git config user.name "carbon-bot"
          git config user.email "carbon@us.ibm.com"
          git merge origin/next
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: v3-upgrade
