name: update v3 branch on next changes
on:
  push:
    branches:
      - next
jobs:
  update-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: merge origin/next into v3
        run: |
          git fetch origin
          git checkout --track origin/v3
          git merge origin/next
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: v3-upgrade
